/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and receive a bearer JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users in the organization */
        get: operations["listUsers"];
        put?: never;
        /** Create a user in the organization */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by id */
        get: operations["getUserById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a user's role and/or status */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations (superadmin) */
        get: operations["listOrganizations"];
        put?: never;
        /** Create an organization (superadmin) */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an organization by id (superadmin) */
        get: operations["getOrganizationById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contact-forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List contact forms in the organization */
        get: operations["listContactForms"];
        put?: never;
        /** Create a contact form */
        post: operations["createContactForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contact-forms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a contact form by id */
        get: operations["getContactFormById"];
        /**
         * Update a contact form
         * @description Replaces the editable fields (name, locales, consent, retention, allowed origins, and the field set) of an existing form. The public form key is immutable, so existing embeds keep working. Audited as contact_form.updated (ADR 0013).
         */
        put: operations["updateContactForm"];
        post?: never;
        /**
         * Delete a contact form (soft delete)
         * @description Soft-deletes the form (ADR 0016 — no physical row deletion): it drops out of every read immediately, while received submissions are retained. Audited as contact_form.deleted (ADR 0013).
         */
        delete: operations["deleteContactForm"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/notification-channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notification channels for a form */
        get: operations["listNotificationChannels"];
        put?: never;
        /** Create a notification channel for a form */
        post: operations["createNotificationChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the organization's audit trail
         * @description Append-only record of every mutation (ADR 0013): who (actor_user_id), what (action / entity_type / entity_id) and the sanitized before/after snapshots. Scoped to the resolved organization; requires the ViewAuditLog capability (admin / superadmin). Ordered newest first.
         */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List submissions in the organization
         * @description Inbox list. Field values are **masked** (charter §11) — the bulk list never discloses raw PII; full content is on the single submission detail. Filtering/search run server-side so raw values are never shipped in bulk to the client.
         */
        get: operations["listSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export submissions as CSV */
        get: operations["exportSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a submission by id */
        get: operations["getSubmissionById"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a submission (data-subject deletion right)
         * @description Soft-deletes the submission (charter §4): it is hidden from the inbox immediately and hard-deleted by the purge job after a grace period (§5). Audited.
         */
        delete: operations["deleteSubmission"];
        options?: never;
        head?: never;
        /** Update a submission's status */
        patch: operations["updateSubmissionStatus"];
        trace?: never;
    };
    "/admin/submissions/{id}/technical-meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Disclose a submission's technical reception metadata (IP / User-Agent)
         * @description Discloses the submission's IP and User-Agent for abuse investigation (ADR 0018). These are excluded from every default payload (charter §2/§11); this endpoint is the only disclosure path and **records an audit event** (`submission_technical_meta.viewed`) before returning. Gated by the `ViewSubmissionTechnicalMeta` capability (admin + superadmin). Not exposed via MCP.
         */
        get: operations["getSubmissionTechnicalMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions/{id}/field-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Correct a submission's stored field values (data-subject correction right)
         * @description Merge-corrects the provided field values (charter §4). Only fields declared on the form may be corrected (purpose limitation). The change is audited as `submission.corrected` with the changed field names — never raw values.
         */
        patch: operations["correctSubmission"];
        trace?: never;
    };
    "/admin/submissions/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notes on a submission */
        get: operations["listSubmissionNotes"];
        put?: never;
        /** Add an operator note to a submission */
        post: operations["addSubmissionNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a submission's attachments (metadata) */
        get: operations["listSubmissionAttachments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions/{id}/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download an attachment's bytes (audited PII access) */
        get: operations["downloadAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions/{id}/handoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a submission's sibling handoff links (status + pointers) */
        get: operations["listSubmissionHandoffs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions/{id}/handoffs/deal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hand a submission to NeNe Deal (create opportunity); same call retries
         * @description Creates an opportunity in NeNe Deal over HTTP (DO D11), idempotent via external_reference = submission_id. Always returns 200 with the resulting link; `handoff_status` is `succeeded` (with `deal_opportunity_id`) or `failed` (with `last_error`, submission untouched). Re-POST to retry. Audited (handoff.created / handoff.retried). Requires the ManageSubmissions capability.
         */
        post: operations["handoffSubmissionToDeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions/{id}/handoffs/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hand a submission to NeNe Invoice (create draft client); same call retries
         * @description Creates a draft client in NeNe Invoice over HTTP (invoice-handoff-contract), idempotent via external_reference = submission_id. Always returns 200 with the resulting link; `handoff_status` is `succeeded` (with `invoice_client_id`) or `failed` (with `last_error`, submission untouched). Re-POST to retry. Audited (handoff.created / handoff.retried). Requires the ManageSubmissions capability.
         */
        post: operations["handoffSubmissionToInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/submissions/{id}/handoffs/vault/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a submission attachment in NeNe Vault; same call retries
         * @description Uploads the attachment bytes to NeNe Vault as a received document over HTTP (DO D12), idempotent per attachment. Always returns 200 with the resulting link; `handoff_status` is `succeeded` (with `vault_document_id`) or `failed` (with `last_error`, attachment untouched). Re-POST to retry. Audited (handoff.created / handoff.retried). Requires the ManageSubmissions capability.
         */
        post: operations["handoffAttachmentToVault"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/forms/{public_form_key}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a file attachment for a form (embed widget)
         * @description Multipart upload (field `file`) for the form's file field (D12). Enforces size cap + content-type allowlist + virus-scan hook. Returns an attachment_id to include as `attachment_ids` on the subsequent submit.
         */
        post: operations["uploadAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/records/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch select options from a NeNe Records entity (read-only)
         * @description Reads a Records entity's select options over HTTP (ADR 0002 — Records is the SSOT; no shared DB) for the form builder to import into a select field. Requires the ManageForms capability. Upstream failures surface as problem details.
         */
        get: operations["fetchRecordsOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List contact forms for AI agents (metadata only)
         * @description Agent read surface (the OpenAPI MCP maps to; ADR 0002 — Contact only, no sibling DB). Returns form structure (fields, locales) only — no secrets, no submitted PII.
         */
        get: operations["agentListForms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List submissions for AI agents (redacted by default)
         * @description Redacted by default — no IP/user-agent, field values masked (charter §11). `include_pii=true` returns raw values and is audit-logged as a bulk PII access (`submission.exported`).
         */
        get: operations["agentListSubmissions"];
        put?: never;
        /**
         * Ingest a submission from a service client (e.g. Concierge) into the inbox
         * @description Creates a submission from a service client (concierge-ingest-contract). `contact_form_id` must belong to the resolved organization. Field values are validated against the form (required, email, consent) like the public submit; audited (`submission.created`) and notified. No autonomous outbound action on personal data (charter §11).
         */
        post: operations["agentIngestSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one submission for AI agents (redacted by default)
         * @description Redacted by default. `include_pii=true` returns raw values and is audit-logged (`submission.viewed`, charter §11).
         */
        get: operations["agentGetSubmission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update submission status (two-step confirmation token, agent write)
         * @description Agent write behind a confirmation token (charter §11 — no autonomous outbound action). Call without `confirmation_token` to get a preview + token (nothing changes); call again with the token to apply (audited). The token binds to this submission id + status.
         */
        patch: operations["agentUpdateSubmissionStatus"];
        trace?: never;
    };
    "/public/forms/{public_form_key}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public form schema for the embed widget */
        get: operations["getPublicFormSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/forms/{public_form_key}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a contact form (embed widget) */
        post: operations["submitPublicForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
            service?: string;
        };
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
        ValidationError: {
            field: string;
            message: string;
            code: string;
        };
        ValidationProblemDetails: components["schemas"]["ProblemDetails"] & {
            errors?: components["schemas"]["ValidationError"][];
        };
        /** @description Per-locale strings keyed by ja / en only (ADR 0011). */
        LocaleMap: {
            [key: string]: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            /** Format: date-time */
            expires_at?: string;
            email?: string;
            /** @enum {string} */
            role: "superadmin" | "admin" | "editor";
            org_id?: number | null;
        };
        UserResponse: {
            id: number;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "superadmin" | "admin" | "editor";
            organization_id?: number | null;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        UserListResponse: {
            items?: components["schemas"]["UserResponse"][];
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            role: "admin" | "editor";
        };
        UpdateUserRequest: {
            /** @enum {string} */
            role?: "admin" | "editor";
            /** @enum {string} */
            status?: "active" | "disabled";
        };
        OrganizationResponse: {
            id: number;
            name: string;
            slug: string;
            external_id?: string | null;
            custom_domain?: string | null;
            plan?: string;
            is_active?: boolean;
        };
        OrganizationListResponse: {
            items?: components["schemas"]["OrganizationResponse"][];
            limit?: number;
            offset?: number;
            total?: number;
        };
        CreateOrganizationRequest: {
            name: string;
            slug: string;
            /** @enum {string} */
            plan?: "free" | "starter" | "pro" | "enterprise";
            external_id?: string;
            custom_domain?: string;
        };
        FormField: {
            id?: number;
            /**
             * @description Closed allowlist (single source of truth: NeneContact\ContactForm\FieldType). My Number and raw payment card numbers are prohibited as any field type and 要配慮個人情報 is never a default (APPI charter §8, Definition of Done A4).
             * @enum {string}
             */
            field_type: "text" | "email" | "textarea" | "select" | "checkbox" | "file" | "honeypot";
            name: string;
            label: components["schemas"]["LocaleMap"];
            required?: boolean;
            options?: {
                [key: string]: unknown;
            }[] | null;
            sort_order?: number;
        };
        ContactFormResponse: {
            id: number;
            name: string;
            public_form_key: string;
            /** @enum {string} */
            default_locale: "ja" | "en";
            locales: ("ja" | "en")[];
            allowed_origins?: string[];
            status?: string;
            consent_required?: boolean;
            consent_label?: components["schemas"]["LocaleMap"] | null;
            /** @description Per-form retention; null uses the documented default (charter §5). */
            retention_days?: number | null;
            fields: components["schemas"]["FormField"][];
        };
        ContactFormListResponse: {
            items?: components["schemas"]["ContactFormResponse"][];
            limit?: number;
            offset?: number;
            total?: number;
        };
        CreateContactFormRequest: {
            name: string;
            /** @enum {string} */
            default_locale: "ja" | "en";
            locales: ("ja" | "en")[];
            allowed_origins?: string[];
            /** @default false */
            consent_required: boolean;
            /** @description Per-locale consent copy (ja/en); required for the default locale when consent_required is true (charter §3). */
            consent_label?: components["schemas"]["LocaleMap"];
            /** @description Optional per-form retention in days; omit to use the documented default (charter §5). */
            retention_days?: number;
            fields: {
                /** @enum {string} */
                field_type: "text" | "email" | "textarea" | "select" | "checkbox" | "file" | "honeypot";
                name: string;
                label: components["schemas"]["LocaleMap"];
                required?: boolean;
                options?: {
                    [key: string]: unknown;
                }[];
            }[];
        };
        PublicFormSchema: {
            public_form_key: string;
            name: string;
            /** @enum {string} */
            default_locale: "ja" | "en";
            locales: ("ja" | "en")[];
            consent_required: boolean;
            consent_label?: components["schemas"]["LocaleMap"] | null;
            fields: components["schemas"]["FormField"][];
        };
        SubmitAccepted: {
            id: number;
            status: string;
        };
        SubmissionResponse: {
            id: number;
            contact_form_id: number;
            /** @enum {string} */
            status: "open" | "in_progress" | "resolved" | "spam";
            /** @description origin: form (public/embed) or service (concierge/import/api) */
            source?: string;
            /** @description embed host page the form was submitted from (referer); safe reception meta (ADR 0018) */
            source_url?: string | null;
            field_values?: {
                [key: string]: unknown;
            };
            consent_label?: components["schemas"]["LocaleMap"] | null;
            /** Format: date-time */
            consent_given_at?: string | null;
            submitted_at?: string | null;
        };
        /** @description Technical reception metadata disclosed only by the audited disclosure endpoint (ADR 0018); never present in any default payload (charter §2/§11). */
        SubmissionTechnicalMetaResponse: {
            id: number;
            /** @description request IP (abuse investigation only) */
            ip?: string | null;
            /** @description request User-Agent (abuse investigation only) */
            user_agent?: string | null;
        };
        RecordsOptionsResponse: {
            source?: string;
            items?: {
                value: string;
                label: string;
            }[];
        };
        AgentFormResponse: {
            id: number;
            name: string;
            public_form_key: string;
            default_locale?: string;
            locales?: string[];
            status?: string;
            consent_required?: boolean;
            retention_days?: number | null;
            fields?: {
                name?: string;
                field_type?: string;
                required?: boolean;
                label?: {
                    [key: string]: string;
                };
            }[];
        };
        AgentFormListResponse: {
            items?: components["schemas"]["AgentFormResponse"][];
        };
        AgentSubmissionResponse: {
            id: number;
            contact_form_id: number;
            status: string;
            source?: string;
            pii_included: boolean;
            /** @description masked unless pii_included */
            field_values?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            consent_given_at?: string | null;
            submitted_at?: string | null;
        };
        AgentSubmissionListResponse: {
            items?: components["schemas"]["AgentSubmissionResponse"][];
            limit?: number;
            offset?: number;
            total?: number;
            pii_included?: boolean;
        };
        IngestSubmissionRequest: {
            /** @enum {string} */
            source: "concierge" | "import" | "api";
            contact_form_id: number;
            field_values: {
                [key: string]: unknown;
            };
            /** @description required when the form requires consent */
            consent?: boolean;
        };
        IngestSubmissionResponse: {
            id: number;
            status: string;
            source: string;
        };
        AgentStatusUpdateRequest: {
            /** @enum {string} */
            status: "open" | "in_progress" | "resolved" | "spam";
            /** @description omit to get a token + preview; pass back to apply */
            confirmation_token?: string;
        };
        /** @description A confirmation challenge (requires_confirmation=true, no change) or the applied result. */
        AgentStatusUpdateResult: {
            requires_confirmation: boolean;
            action?: string;
            confirmation_token?: string;
            /** Format: date-time */
            expires_at?: string | null;
            preview?: {
                submission_id?: number;
                current_status?: string;
                requested_status?: string;
            };
            confirmed?: boolean;
            submission?: components["schemas"]["AgentSubmissionResponse"];
        };
        SubmissionLinkResponse: {
            id: number;
            submission_id: number;
            attachment_id?: number | null;
            /** @enum {string} */
            target: "deal" | "vault" | "invoice";
            /** @enum {string} */
            handoff_status: "pending" | "succeeded" | "failed";
            deal_opportunity_id?: string | null;
            vault_document_id?: string | null;
            invoice_client_id?: string | null;
            last_error?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        SubmissionLinkListResponse: {
            items?: components["schemas"]["SubmissionLinkResponse"][];
        };
        AttachmentResponse: {
            id: number;
            field_name: string;
            original_filename: string;
            content_type: string;
            size_bytes: number;
            /** @enum {string} */
            scan_status: "skipped" | "clean" | "infected";
            /** Format: date-time */
            created_at?: string | null;
        };
        AttachmentListResponse: {
            items?: components["schemas"]["AttachmentResponse"][];
        };
        AttachmentUploadResponse: {
            attachment_id: number;
            field_name?: string;
            content_type?: string;
            size_bytes?: number;
        };
        SubmissionListResponse: {
            /** @description Submissions with masked field values (charter §11). */
            items?: components["schemas"]["SubmissionResponse"][];
            limit?: number;
            offset?: number;
            total?: number;
            /** @description Per-status totals for the current query/form/date filter (status filter ignored). */
            status_counts?: {
                [key: string]: number;
            };
        };
        AuditEventResponse: {
            id?: number;
            /** @description User who performed the change; null for system/CLI actions. */
            actor_user_id?: number | null;
            organization_id?: number | null;
            /** @description e.g. submission.status_updated, contact_form.updated, organization.created */
            action?: string;
            entity_type?: string;
            entity_id?: number | null;
            /** @description Sanitized snapshot before the change (null for creates). */
            before?: {
                [key: string]: unknown;
            } | null;
            /** @description Sanitized snapshot after the change (null for deletes). */
            after?: {
                [key: string]: unknown;
            } | null;
            created_at?: string | null;
        };
        AuditEventListResponse: {
            items?: components["schemas"]["AuditEventResponse"][];
            limit?: number;
            offset?: number;
            total?: number;
        };
        UpdateSubmissionStatusRequest: {
            /** @enum {string} */
            status: "open" | "in_progress" | "resolved" | "spam";
        };
        CorrectSubmissionRequest: {
            /** @description Field name/value pairs to correct; keys must be fields declared on the form. */
            field_values: {
                [key: string]: unknown;
            };
        };
        SubmissionNoteResponse: {
            id: number;
            submission_id: number;
            author_user_id?: number | null;
            body: string;
            created_at?: string | null;
        };
        SubmissionNoteListResponse: {
            items?: components["schemas"]["SubmissionNoteResponse"][];
        };
        AddSubmissionNoteRequest: {
            body: string;
        };
        NotificationChannelResponse: {
            id: number;
            contact_form_id: number;
            /** @enum {string} */
            channel_type: "email" | "slack" | "chatwork" | "webhook";
            is_enabled?: boolean;
        };
        NotificationChannelListResponse: {
            items?: components["schemas"]["NotificationChannelResponse"][];
        };
        CreateNotificationChannelRequest: {
            contact_form_id: number;
            /** @enum {string} */
            channel_type: "email" | "slack" | "chatwork" | "webhook";
            /** @description Channel-specific keys (encrypted at rest). email: recipient; slack: webhook_url; chatwork: api_token, room_id; webhook: url, secret (HMAC-SHA256 signing). */
            config: {
                [key: string]: unknown;
            };
            is_enabled?: boolean;
        };
    };
    responses: {
        /** @description RFC 9457 Problem Details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Validation failed */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblemDetails"];
            };
        };
    };
    parameters: {
        IdPath: number;
        PublicFormKeyPath: string;
        Limit: number;
        Offset: number;
        /** @description When true, returns raw (unmasked) field values; audit-logged (charter §11). */
        IncludePii: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationListResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    getOrganizationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listContactForms: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contact form list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactFormListResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    createContactForm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactFormRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactFormResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    getContactFormById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contact form */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactFormResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    updateContactForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactFormRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactFormResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    deleteContactForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listNotificationChannels: {
        parameters: {
            query: {
                contact_form_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannelListResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    createNotificationChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNotificationChannelRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannelResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                /** @description Free-text match over action / entity type / "entity_type */
                q?: string;
                /** @description Inclusive lower bound on created_at (YYYY-MM-DD). */
                from?: string;
                /** @description Inclusive upper bound on created_at (YYYY-MM-DD). */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit event list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventListResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    listSubmissions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                status?: "open" | "in_progress" | "resolved" | "spam";
                contact_form_id?: number;
                /** @description Inclusive lower bound on submitted_at (YYYY-MM-DD). */
                from?: string;
                /** @description Inclusive upper bound on submitted_at (YYYY-MM-DD). */
                to?: string;
                /** @description Free-text match over submitted content (matched server-side; raw values are not returned). */
                q?: string;
                /** @description Row order. Defaults to newest first. */
                sort?: "date_desc" | "date_asc" | "status" | "form";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionListResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    exportSubmissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getSubmissionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    deleteSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    updateSubmissionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubmissionStatusRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    getSubmissionTechnicalMeta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Technical reception metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionTechnicalMetaResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    correctSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectSubmissionRequest"];
            };
        };
        responses: {
            /** @description Corrected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    listSubmissionNotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Note list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionNoteListResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    addSubmissionNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSubmissionNoteRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionNoteResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    listSubmissionAttachments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentListResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    downloadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
                attachmentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listSubmissionHandoffs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Handoff link list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionLinkListResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    handoffSubmissionToDeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Handoff attempt recorded (see handoff_status for the outcome) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionLinkResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    handoffSubmissionToInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Handoff attempt recorded (see handoff_status for the outcome) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionLinkResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    handoffAttachmentToVault: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
                attachmentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Handoff attempt recorded (see handoff_status for the outcome) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionLinkResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    uploadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_form_key: components["parameters"]["PublicFormKeyPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentUploadResponse"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
            429: components["responses"]["Problem"];
        };
    };
    fetchRecordsOptions: {
        parameters: {
            query: {
                /** @description The Records entity key. */
                source: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Options */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordsOptionsResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
            502: components["responses"]["Problem"];
        };
    };
    agentListForms: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Form list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentFormListResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    agentListSubmissions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                /** @description When true, returns raw (unmasked) field values; audit-logged (charter §11). */
                include_pii?: components["parameters"]["IncludePii"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission list (redacted unless include_pii=true) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSubmissionListResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    agentIngestSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestSubmissionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestSubmissionResponse"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
        };
    };
    agentGetSubmission: {
        parameters: {
            query?: {
                /** @description When true, returns raw (unmasked) field values; audit-logged (charter §11). */
                include_pii?: components["parameters"]["IncludePii"];
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission (redacted unless include_pii=true) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSubmissionResponse"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    agentUpdateSubmissionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Either a confirmation challenge (no change) or the applied result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentStatusUpdateResult"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
            503: components["responses"]["Problem"];
        };
    };
    getPublicFormSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_form_key: components["parameters"]["PublicFormKeyPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Form schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicFormSchema"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    submitPublicForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_form_key: components["parameters"]["PublicFormKeyPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    consent?: boolean;
                    /** @description Ids returned by the attachment upload endpoint (D12). */
                    attachment_ids?: number[];
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitAccepted"];
                };
            };
            /** @description Accepted silently (honeypot tripped) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["ValidationProblem"];
            429: components["responses"]["Problem"];
        };
    };
}
